/*Text Hero custom component */
export const TextHeroStyle = {
  container: {
    width: '100%',
    maxWidth: { md: '1366px' },
    height: { md: '565px', sm: '400px', xs: 'auto' },
    position: 'relative',
  },
  image1: {
    width: '70%',
    height: '100%',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    left: 0,
    zIndex: 1,
    display: { xs: 'none', sm: 'block', md: 'block' },
  },
  image2: {
    width: '70%',
    height: '100%',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    right: 0,
    zIndex: 2,
    display: { xs: 'none', sm: 'block', md: 'block' },
  },
  paragraphText: {
    width: { md: '626px', sm: '400px', xs: '100%' },
    height: { md: '344px', sm: '285px', xs: '283px' },
    borderRadius: '5px',
    backgroundSize: { md: 'cover', sm: 'contain', xs: 'contain' },
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    zIndex: { md: '3', sm: '3' },
    position: 'relative',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: { md: '48px', sm: '20px', xs: '10px' },
    backgroundColor: 'transparent !important',
  },
  paragraphTextP: {
    fontFamily: 'Poppins',
    fontSize: { md: '28px', sm: '20px', xs: '18px' },
    fontWeight: { md: 300, sm: 500, xs: 500 },
    lineHeight: { md: '42px', sm: '32px', xs: '30px' },
    textAlign: 'center',
    padding: { md: '20px', sm: '20px', xs: '23px' },
  },
}
