import { BorderTop, PaddingTwoTone } from '@mui/icons-material'

export const B2BAccountCreateFormStyles = {
  buttonStackStyle: {
    width: { xs: '100%' },
    flexDirection: { xs: 'row', md: 'row' },
    justifyContent: { xs: 'center', md: 'end' },
  },
  buttonSection: {
    BorderTop: '1px solid #EDEDED',
    PaddingTop: '15px',
  },
  buttonPrimary: {
    width: 'auto',
    // flexDirection: { xs: 'column', md: 'row' },
    // justifyContent: 'end',
    backgroundColor: '#30299A',
    color: '#FFF',
    textAlign: 'center',
    /* Button 2 (Pills) */
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '24px',
    borderRadius: '0px 26px',
    border: '1px solid #30299A',
    padding: '12px 30px',
    '&:hover': {
      backgroundColor: '#4C47C4',
      border: '1px solid #4C47C4',
    },
    marginLeft: '20px',
  },
  buttonSecondary: {
    width: 'auto',
    // flexDirection: { xs: 'column', md: 'row' },
    // justifyContent: 'end',
    backgroundColor: '#fff',
    color: '#30299A',
    textAlign: 'center',
    /* Button 2 (Pills) */
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '24px',
    borderRadius: '0px 26px',
    border: '1px solid #30299A',
    padding: '12px 30px',
    '&:hover': {
      backgroundColor: '#E3E2FF;',
      border: '1px solid #E3E2FF',
    },
  },
  buttonDisabled: {
    width: 'auto',
    // flexDirection: { xs: 'column', md: 'row' },
    // justifyContent: 'end',
    backgroundColor: '#8D8D8D !important',
    color: '#fff',
    textAlign: 'center',
    /* Button 2 (Pills) */
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '24px',
    borderRadius: '0px 26px',
    border: '1px solid #8D8D8D',
    padding: '12px 30px',
    marginLeft: '20px',
  },
  textStyle: {
    color: '#020027',
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '300',
    lineHeight: '25px',
  },
  loginLinksText: {
    color: '#020027',
    fontFamily: 'Poppins',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '300',
    lineHeight: '25px',
    paddingRight: '10px',
  },
}
